In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(-1)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0] > 0.5:
        print("Rock")
    elif prediction[0][1] > 0.5:
        print("Paper")
    elif prediction[0][2] > 0.5:
        print("Sciccors")    
    else:
        print("Nothing")    
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-04-01 05:45:52.522417: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/shah/miniconda3/envs/Computer_Vision/lib/python3.9/site-packages/cv2/../../lib64:
2022-04-01 05:45:52.522436: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-04-01 05:45:53.707973: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/shah/miniconda3/envs/Computer_Vision/lib/python3.9/site-packages/cv2/../../lib64:
2022-04-01 05:45:53.707994: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-01 05:45:53.708006: I tensorflow/stream_executo

Nothing
[[1.9598304e-01 2.5133005e-01 2.4531363e-04 5.5244154e-01]]
Nothing
[[4.9659395e-01 3.4049012e-02 1.6308686e-04 4.6919388e-01]]
Rock
[[5.1191670e-01 4.6622604e-02 3.2847619e-04 4.4113216e-01]]
Rock
[[8.0741119e-01 1.2039022e-02 2.6140569e-04 1.8028839e-01]]
Nothing
[[9.0010181e-02 1.6539346e-01 1.2848933e-05 7.4458349e-01]]
Nothing
[[7.0698746e-02 3.6372709e-01 8.0218069e-06 5.6556612e-01]]
Nothing
[[4.7039911e-02 1.3635196e-01 1.4488899e-05 8.1659371e-01]]
Nothing
[[4.4919100e-02 1.0345955e-01 1.6509708e-05 8.5160482e-01]]
Nothing
[[3.7873697e-02 1.1679613e-01 1.3922964e-05 8.4531623e-01]]
Nothing
[[4.0725298e-02 6.0211595e-02 1.4525206e-05 8.9904863e-01]]
Nothing
[[4.1891955e-02 9.6583977e-02 1.6627690e-05 8.6150742e-01]]
Nothing
[[7.1271606e-02 7.0048764e-02 1.6883256e-05 8.5866278e-01]]
Nothing
[[2.0464869e-02 6.8946280e-02 1.1231458e-05 9.1057760e-01]]
Nothing
[[6.2662557e-02 6.5941453e-02 1.9027564e-05 8.7137693e-01]]
Nothing
[[9.9011816e-02 1.5582009e-01 1.4910937e-05 7.